### ISSUE TITLE
Support colour terminal output

### ISSUE THREAD

**Issue by ElFeesho** [brave-warrior/TravisClient-Android#7]
The following output in the build log view:

```
[32;1mThe command "cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make" exited with 0.[0m

Done. Your build exited with 0.
```

Could be interpreted and displayed as colourised text, using `ForegroundSpannable`.

**Comment by brave-warrior** [comment]
@ElFeesho The build log is a raw text (txt file in S3 storage). In app it's shown inside the WebView, because TextView control and similar has text size limitation. So it's possible to make it colourised using html.

However, the title of the build is already colourised and shows the state of the build (e.g. failed, passed etc.)

**Comment by ElFeesho** [comment]
Good shout! I might play around with it and I'll submit a PR if I think the approach is any good. Cheers :+1:

**Comment by brave-warrior** [comment]
But isn't the colourised title in build details enough?

**Comment by ElFeesho** [comment]
After looking into it, I think the amount of work and added complexity is definitely not worth while right now. If you ever get bored however... 

Like you said the colourised title and build details are good enough, the use case I was angling at was you have a failed build, so you dig into the build log to figure out what test was failing; having coloured output would make that easier.

**Comment by brave-warrior** [comment]
Maybe, but you wanted to highlight only the last line of the output with the result, what makes actually no sense.
